import Anthropic from "@anthropic-ai/sdk";

import type { AnalyticsData, ClientConfig } from "@/lib/types";
import { formatDuration, formatNumber, formatPercent, trendLabel } from "@/lib/analytics";

import styles from "./ai-summary.module.css";

type AISummaryProps = {
  client: ClientConfig;
  analytics: AnalyticsData;
};

async function generateSummary(client: ClientConfig, analytics: AnalyticsData): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return "";

  const { summary, sources, period } = analytics;

  const prompt = `You are a website analytics assistant for ${client.client}.
Write a concise 3-paragraph plain-English summary for the business owner.
Be specific, actionable, encouraging. No jargon. No markdown.
Data: ${JSON.stringify({
    period: `Last ${period.days} days`,
    sessions: formatNumber(summary.sessions),
    trend: trendLabel(summary.trend) + " vs previous period",
    users: formatNumber(summary.users),
    pageviews: formatNumber(summary.pageviews),
    bounceRate: formatPercent(summary.bounceRate),
    avgSessionDuration: formatDuration(summary.avgSessionDurationSeconds),
    topSource: `${sources[0]?.source} / ${sources[0]?.medium}`,
    keyConversions: client.website.key_conversions,
  })}
Tone: ${client.brand.tone_of_voice}
Business: ${client.brand.brand_personality}`;

  const anthropic = new Anthropic({ apiKey });
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 1024,
    messages: [{ role: "user", content: prompt }],
  });

  const block = message.content[0];
  return block.type === "text" ? block.text : "";
}

export async function AISummary({ client, analytics }: AISummaryProps) {
  const summary = await generateSummary(client, analytics);

  if (!summary) {
    return (
      <div className={styles.wrapper}>
        <p className={styles.label}>AI summary</p>
        <p className={styles.placeholder}>
          Add <code>ANTHROPIC_API_KEY</code> to your environment to enable AI-generated summaries.
        </p>
      </div>
    );
  }

  return (
    <div className={styles.wrapper}>
      <p className={styles.label}>AI summary</p>
      <p className={styles.text}>{summary}</p>
      <p className={styles.model}>Generated by Claude</p>
    </div>
  );
}
