import Anthropic from "@anthropic-ai/sdk";

import type { AnalyticsData, ClientConfig } from "@/lib/types";
import { formatDuration, formatNumber, formatPercent, trendLabel } from "@/lib/analytics";

import styles from "./ai-summary.module.css";

type AISummaryProps = {
  client: ClientConfig;
  analytics: AnalyticsData;
};

async function generateSummary(client: ClientConfig, analytics: AnalyticsData): Promise<string> {
  const apiKey = process.env.ANTHROPIC_API_KEY;
  if (!apiKey) return "";

  const { summary, sources, topPages, period } = analytics;

  const prompt = `You are a digital marketing analyst. Write a concise 2–3 sentence performance summary for ${client.name}, a ${client.business.type} in ${client.business.location}.

Analytics for the last ${period.days} days:
- Sessions: ${formatNumber(summary.sessions)} (${trendLabel(summary.trend)} vs previous period)
- Users: ${formatNumber(summary.users)}
- Pageviews: ${formatNumber(summary.pageviews)}
- Bounce rate: ${formatPercent(summary.bounceRate)}
- Avg session duration: ${formatDuration(summary.avgSessionDurationSeconds)}
- Top source: ${sources[0]?.source} / ${sources[0]?.medium} (${sources[0] ? Math.round((sources[0].sessions / summary.sessions) * 100) : 0}%)
- Top page: ${topPages[0]?.path} (${formatNumber(topPages[0]?.pageviews ?? 0)} views)

Tone: ${client.toneOfVoice}

Keep it factual and actionable. Do not use bullet points. Do not use headings.`;

  const anthropic = new Anthropic({ apiKey });
  const message = await anthropic.messages.create({
    model: "claude-sonnet-4-20250514",
    max_tokens: 256,
    messages: [{ role: "user", content: prompt }],
  });

  const block = message.content[0];
  return block.type === "text" ? block.text : "";
}

export async function AISummary({ client, analytics }: AISummaryProps) {
  const summary = await generateSummary(client, analytics);

  if (!summary) {
    return (
      <div className={styles.wrapper}>
        <p className={styles.label}>AI summary</p>
        <p className={styles.placeholder}>
          Add <code>ANTHROPIC_API_KEY</code> to your environment to enable AI-generated summaries.
        </p>
      </div>
    );
  }

  return (
    <div className={styles.wrapper}>
      <p className={styles.label}>AI summary</p>
      <p className={styles.text}>{summary}</p>
      <p className={styles.model}>Generated by Claude</p>
    </div>
  );
}
